name: InstanceGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - tqdm
  - imageio
  - plyfile
  - torch_scatter
  - jaxtyping
  - opencv-python
  - open3d
  - bitarray
  - einops
  # - pytorch3d
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn